<?php
/**
 * Listrak Remarketing Magento Extension Ver. 1.1.9
 *
 * PHP version 5
 *
 * @category  Listrak
 * @package   Listrak_Remarketing
 * @author    Listrak Magento Team <magento@listrak.com>
 * @copyright 2013 Listrak Inc
 * @license   http://s1.listrakbi.com/licenses/magento.txt License For Customer Use of Listrak Software
 * @link      http://www.listrak.com
 */

/* @var Listrak_Remarketing_Helper_Data $helper */
$helper = Mage::helper('remarketing');
$scaEnabled = $helper->scaEnabled();

/* @var bool $isSecure */
$isSecure = Mage::app()->getStore()->isCurrentlySecure();
?>
<script type="text/javascript">
    Listrak_Remarketing = new function() {
        this.updateCart = function() {
            <?php
            if ($scaEnabled) {
                $updateUrl = Mage::getUrl('remarketing/ajax/cart', array('_forced_secure' => $isSecure));
                echo "new Ajax.Request('{$updateUrl}');";
            }
            ?>
        };

        this.track = function() {
            <?php
            if ($scaEnabled) {
                $trackUrl = Mage::getUrl('remarketing/ajax/track', array('_forced_secure' => $isSecure));
                echo "new Ajax.Request('{$trackUrl}');";
            }
            ?>
        };
    };
</script>
