<?php
/**
 * Listrak Remarketing Magento Extension Ver. 1.1.5
 *
 * PHP version 5
 *
 * @category  Listrak
 * @package   Listrak_Remarketing
 * @author    Listrak Magento Team <magento@listrak.com>
 * @copyright 2013 Listrak Inc
 * @license   http://s1.listrakbi.com/licenses/magento.txt License For Customer Use of Listrak Software
 * @link      http://www.listrak.com
 */

?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">
            <?php echo Mage::helper('catalog')->__('Category and Subcategory') ?>
        </h4>
    </div>
    <fieldset>

        <legend>
            <?php echo Mage::helper('remarketing')->__('Product Categories') ?>
        </legend>
        <table cellspacing="0" class="form-list"
               id="table_productattributes_categories">
            <tr>
                <td class="label">
                    <label for="categories_source">
                        <?php echo Mage::helper('remarketing')->__('Source') ?>
                    </label>
                </td>
                <td class="value">
                    <select id="categories_source" name="categories_source"
                            class="select">
                        <option value="default"
                            <?php
                            if ($this->getCategoriesSource() == 'default') {
                                echo 'selected="selected"';
                            }
                            ?>
                        >
                            <?php
                            echo Mage::helper('remarketing')
                                ->__('Use Catalog Configuration')
                            ?>
                        </option>
                        <option value="attributes"
                            <?php if ($this->getCategoriesSource() == 'attributes') {
                                echo 'selected="selected"';
                            }
                            ?>
                        >
                            <?php
                            echo Mage::helper('remarketing')
                                ->__('Map from Product Attributes')
                            ?>
                        </option>
                    </select>                  
                    <input type="hidden" id="categories_source_default"
                           value="<?php echo $this->escapeHtml($this->getConfigCategoriesSource()); ?>"
                    />

                    <?php
                    $_checked = $this->getUseConfigCategoriesSource()
                        ? 'checked="checked"'
                        : ''
                    ?>
                    <input type="checkbox" id="categories_use_config_source"
                           name="use_config_categories_source"
                           value="1" <?php echo $_checked ?>
                           onclick="toggleValueElements(this, this.parentNode);"
                           class="checkbox"/>
                    <label for="categories_use_config_source" class="normal">
                        <?php
                        echo Mage::helper('catalog')
                            ->__('Use Listrak Configuration Settings')
                        ?>
                    </label>
                </td>
                <td class="value scope-label">
                    <?php
                    echo Mage::helper('remarketing')
                        ->__('[GLOBAL]')
                    ?>
                </td>
            </tr>

            <tr>
                <td class="label">
                    <label for="categories_category_attribute">
                        <?php
                        echo Mage::helper('remarketing')
                            ->__('Category Attribute')
                        ?>
                    </label>
                </td>
                <td class="value">
                    <select id="categories_category_attribute"
                            name="categories_category_attribute"
                            class="listrak_validate_unique_selection_category_attribute select">
                        <option value="">- No Category Attribute -</option>
                        <?php foreach ($this->getAttributeOptions() as $key => $option): ?>
                            <?php
                            $_selected = ($key == $this->getCategoryAttributeCode())
                                ? 'selected="selected"'
                                : ''
                            ?>
                            <option
                                value="<?php echo $key ?>" <?php echo $_selected ?>>
                                <?php echo $option ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <td class="value scope-label">
                    <?php echo Mage::helper('remarketing')->__('[GLOBAL]') ?>
                </td>
            </tr>

            <tr>
                <td class="label">
                    <label for="categories_subcategory_attribute">
                        <?php
                        echo Mage::helper('catalog')
                            ->__('Subcategory Attribute')
                        ?>
                    </label>
                </td>
                <td class="value">
                    <select id="categories_subcategory_attribute"
                            name="categories_subcategory_attribute"
                            class="listrak_validate_unique_selection_subcategory_attribute select">
                        <option value="">- No Subcategory Attribute -</option>
                        <?php foreach ($this->getAttributeOptions() as $key => $option): ?>
                            <?php
                            $_selected
                                = ($key == $this->getSubcategoryAttributeCode())
                                    ? 'selected="selected"'
                                    : ''
                            ?>
                            <option
                                value="<?php echo $key ?>" <?php echo $_selected ?>>
                                <?php echo $option ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <td class="value scope-label">
                    <?php echo Mage::helper('catalog')->__('[GLOBAL]') ?>
                </td>
            </tr>
        </table>
        <script type="text/javascript">
            //<![CDATA[
            var categoriesVisible = null;
            function changeCategoriesSourceOption() {
                var configSource = $('categories_use_config_source').checked;
                var catSource = configSource
                    ? $('categories_source_default').value
                    : $('categories_source').value;
                categoriesVisible = catSource == 'attributes';

                var catRow = $('categories_category_attribute').up('tr');
                var subcatRow = $('categories_subcategory_attribute').up('tr');

                if (categoriesVisible) {
                    catRow.show();
                    subcatRow.show();
                }
                else {
                    catRow.hide();
                    subcatRow.hide();
                }
            }

            toggleValueElements(
                $('categories_use_config_source'),
                $('categories_use_config_source').parentNode
            );

            Event.observe(
                $('categories_source'), 'change',
                changeCategoriesSourceOption
            );
            Event.observe(
                $('categories_use_config_source'), 'change',
                changeCategoriesSourceOption
            );
            changeCategoriesSourceOption();

            Validation.add(
                'listrak_validate_unique_selection_category_attribute',
                'You may select an attribute only once.',
                function (attr) {
                    if (attr == '' || !categoriesVisible)
                        return true;

                    // make sure brand doesn't have this value
                    var brandAttr = $('brand_attribute');
                    return brandAttr == null || !(
                            brandAttr.selectedIndex > 0 && brandAttr.value == attr
                        );
                }
            );

            Validation.add(
                'listrak_validate_unique_selection_subcategory_attribute',
                'You may select an attribute only once.',
                function (attr) {
                    if (attr == '' || !categoriesVisible)
                        return true;

                    // make sure neither brand nor category has the same value
                    var brandAttr = $('brand_attribute');
                    var catAttr = $('categories_category_attribute');
                    return ((brandAttr == null
                        || !(brandAttr.selectedIndex > 0 && brandAttr.value == attr))
                        && !(catAttr.selectedIndex > 0 && catAttr.value == attr));
                }
            );
            //]]>
        </script>
    </fieldset>
</div>
