<?php
$helper = Mage::helper('pixlee');
$nativeCategoryId = $this->category_id;
$pixleeCategoryWidgetId = $this->getCategoryWidgetId();
$pixleeAccountApiKey = $this->getAccountApiKey();
if($helper->isActive() && !empty($nativeCategoryId) && 
    isset($pixleeAccountApiKey) && !empty($pixleeAccountApiKey) &&
    isset($pixleeCategoryWidgetId) && !empty($pixleeCategoryWidgetId)):
?>
<div id="pixlee_container"></div>
<div id="pixlee_widget_master_container"></div>
<script id="pixlee_script">

	window.PixleeAsyncInit = function() {
	    Pixlee.init({
	        apiKey: '<?php echo $pixleeAccountApiKey; ?>'
	    });
	    Pixlee.addCategoryWidget({
        widgetId: <?php echo $pixleeCategoryWidgetId; ?>,
    		nativeCategoryId: <?php echo $nativeCategoryId; ?>,
        ecomm_platform: 'magento'
	    });
	};
</script>
<script src="https://assets.pixlee.com/assets/pixlee_widget_1_0_0.js"></script>

<?php elseif(empty($pixleeAccountApiKey)): ?>
	<!-- Pixlee not installed for the website Skipping CDP widget. -->	
<?php elseif(empty($pixleeCategoryWidgetId)): ?>
	<!-- Please enter a category widget ID in the admin panel to display Pixlee CDP galleries. -->	
<?php elseif(empty($nativeCategoryId)): ?>
  <!-- Could not display the Pixlee gallery. No product SKU found. Try explicitly setting one with the "setProductSku" function after creating the block. -->
<?php else: ?>
  <!-- Could not display the Pixlee gallery. Make sure all the required credentials are saved in the Magento admin panel! -->
<?php endif; ?>