<?php
$helper = Mage::helper('pixlee');
$productSku = $this->getProductSku();
$pixleeAccountId = $this->getAccountId();
$pixleeWidgetId = $this->getWidgetId();
$pixleeAccountApiKey = $this->getAccountApiKey();

if($helper->isActive() && !empty($productSku) && 
    isset($pixleeAccountId) && !empty($pixleeAccountId) &&
    isset($pixleeAccountApiKey) && !empty($pixleeAccountApiKey) &&
    isset($pixleeWidgetId) && !empty($pixleeWidgetId)):
?>

<div id="pixlee_container"></div>
<div id="pixlee_widget_master_container"></div>
<script id="pixlee_script">
	window.PixleeAsyncInit = function() {
	    Pixlee.init({apiKey: '<?php echo $pixleeAccountApiKey; ?>'});
	    Pixlee.addProductWidget({
        widgetId: <?php echo $pixleeWidgetId; ?>,
    		skuId: '<?php echo $productSku; ?>',
    		accountId:<?php echo $pixleeAccountId; ?>
	    });
	};
</script>
<script src="https://assets.pixlee.com/assets/pixlee_widget_1_0_0.js"></script>

<?php elseif(empty($pixleeAccountId)): ?>
	<!-- Pixlee not installed for the website Skipping PDP widget. -->	
<?php elseif(empty($pixleeWidgetId)): ?>
	<!-- Please enter a product widget ID in the admin panel to display Pixlee PDP galleries. -->	
<?php elseif(empty($productSku)): ?>
  <!-- Could not display the Pixlee gallery. No product SKU found. Try explicitly setting one with the "setProductSku" function after creating the block. -->
<?php else: ?>
  <!-- Could not display the Pixlee gallery. Make sure all the required credentials are saved in the Magento admin panel! -->
<?php endif; ?>