 <style>
#ratelinks {display:none;}
</style>
<div class="homepage">
    <div class="hero">
        <?php $this->renderWidgets('hero'); ?>
    </div>
	</div>
	    <div class="fullbleed">
        <?php $this->renderWidgets('fullbleed'); ?>
    </div>
    <div class="section">
        <?php $this->renderWidgets('section'); ?>
    </div>
	<style>
	.MegansBlockHeadline{
	font-size: 2.6em;
	font-weight: normal;
	font-style: normal;
	margin: auto;
	padding: 20px;
	text-align: center;
	}
	</style>
	<div class="MegansBlock">
		<div class="MegansBlockHeadline">#P&Uuml;RBEAUTY</div>
		<script src="https://cdn.dashhudson.com/web/js/board-carousel-embed.js" type="text/javascript" data-name="dhboard-carousel" data-id="205916259" data-board-id="10216" data-row-size="5" data-gap-size="4" data-mobile-row-size="3" data-mobile-gap-size="2" show-header="0" data-autoplay="true" data-call-to-action="shop_now"></script>
    <div class="press">
        <?php $this->renderWidgets('press'); ?>
    </div>
</div>