<div class="main">
	<div class="hero">
		<?php $this->renderWidgets('hero'); ?>
	</div>
	<div class="results">
		<?php $this->renderWidgets('results'); ?>
	</div>
	<div class="benefits">
		<?php $this->renderWidgets('benefits'); ?>
	</div>
	<div class="section">
		<?php $this->renderWidgets('section'); ?>
	</div>
	<div class="videocarousel">
		<?php $this->renderWidgets('videocarousel'); ?>
	</div>
	<div class="press">
	</div>	
</div>
