<div class="spas-section">

    <h2 class="spas-title">spas of the month</h2>

    <ul class="spas-list">
        <li>
            <div class="spa-image">
                <div class="spa-image-outer">
                    <div class="spa-image-inner">
                        <img src="media/catalog/product/4/-/4-1.jpg" alt="spa-img">
                    </div>
                </div>
            </div>
            <div class="spa-content" data-is-elite="1">
                <div class="spa-content-outer">
                    <div class="spa-content-inner">
                        <div class="spa-content-middle">
                            <div class="store-list-elite"></div>
                            <div class="spa-name">Medula, NYC</div>
                            <div class="store-list-text spa-city">New York, NY</div>
                            <div class="store-list-text spa-description">Say something great about this spa! Our concentrated therapy is designed to.</div>
                            <div class="address">
                                <div class="store-list-text"><span class="spa-street">1133 Broadway, Suite 1314</span></div>
                                <div class="store-list-text"><span class="spa-city">New York,</span><span class="spa-postal-code"> New York</span><span class="spa-country"> 10010</span></div>
                                <div class="store-list-text"><span class="spa-phone"></span>917.750.2895</div>
                            </div>
                    <!--      TODO BE: please add data-attr data-lat="" data-lng=""  -->
                            <a href="javascript:void(0)" class="store-list-btn" data-lat="" data-lng="">Directions</a>
                            <a href="#" class="store-list-link">fableskincare.com</a>
                        </div>
                    </div>
                </div>
            </div>
        </li>

        <li>
            <div class="spa-image">
                <div class="spa-image-outer">
                    <div class="spa-image-inner">
                        <img src="media/catalog/product/4/-/4-1.jpg" alt="spa-img">
                    </div>
                </div>
            </div>
            <div class="spa-content" data-is-elite="1">
                <div class="spa-content-outer">
                    <div class="spa-content-inner">
                        <div class="spa-content-middle">
                            <div class="store-list-elite"></div>
                            <div class="spa-name">Mariaoara Skincare</div>
                            <div class="store-list-text spa-city">Atlanta, GA</div>
                            <div class="store-list-text spa-description">Say something great about this spa! Our concentrated therapy is designed to.</div>
                            <div class="address">
                                <div class="store-list-text"><span class="spa-street">1133 Broadway, Suite 1314</span></div>
                                <div class="store-list-text"><span class="spa-city">New York,</span><span class="spa-postal-code"> New York</span><span class="spa-country"> 10010</span></div>
                                <div class="store-list-text"><span class="spa-phone"></span>917.750.2895</div>
                            </div>
                            <a href="javascript:void(0)" class="store-list-btn" data-lat="" data-lng="">Directions</a>
                            <a href="#" class="store-list-link">fableskincare.com</a>
                        </div>
                    </div>
                </div>
            </div>
        </li>

        <li>
            <div class="spa-image">
                <div class="spa-image-outer">
                    <div class="spa-image-inner">
                        <img src="media/catalog/product/4/-/4-1.jpg" alt="spa-img">
                    </div>
                </div>
            </div>
            <div class="spa-content" data-is-elite="1">
                <div class="spa-content-outer">
                    <div class="spa-content-inner">
                        <div class="spa-content-middle">
                            <div class="store-list-elite"></div>
                            <div class="spa-name">Bella Donna</div>
                            <div class="store-list-text spa-city">Beverly Hills, CA</div>
                            <div class="store-list-text spa-description">Say something great about this spa! Our concentrated therapy is designed to.</div>
                            <div class="address">
                                <div class="store-list-text"><span class="spa-street">1133 Broadway, Suite 1314</span></div>
                                <div class="store-list-text"><span class="spa-city">New York,</span><span class="spa-postal-code"> New York</span><span class="spa-country"> 10010</span></div>
                                <div class="store-list-text"><span class="spa-phone"></span>917.750.2895</div>
                            </div>
                            <a href="javascript:void(0)" class="store-list-btn" data-lat="" data-lng="">Directions</a>
                            <a href="#" class="store-list-link">fableskincare.com</a>
                        </div>
                    </div>
                </div>
            </div>
        </li>

    </ul>

</div>
