<style>
    h2 {
        padding: 10px;
        border-top: 1px solid #e6e6e6;
        border-bottom: 1px solid #e6e6e6;
        text-align: center;
        width: 100%;

    }

    .subsection {
        float: left;
        width: 30%;
        padding: 10px;
    }

    .subsection span {
        font-weight: bold;
        text-align: center;
    }
	ul {
		width:100%;
	}

    .section-wrapper {
        width: 90%;
        margin-left: auto;
        margin-right: auto;
    }
</style>
<div class="section-wrapper">
    <?php
    $sections = $this->getSections();
    foreach ($sections as $section) {
        ?>
        <h2><?php echo $section->getSectionName() ?></h2>
        <?php $subIds = $section->getSubsectionId();
        $subIds = explode(',', $subIds);
        $subsections = $this->getSubSections($subIds);
        foreach ($subsections as $subsection) {
            ?>
            <div class="subsection"><span><?php echo $subsection->getSubsectionName() ?></span>
                <ul class="items">
                    <?php $media = $this->getMediaInfo($subsection->getEntityId());
                    foreach ($media as $m) {
                        ?>
                        <li>
                            <a href="<?php echo $this->getUrl('mediacenter/index/download') . '?file_name=' . $m->getFileName() ?>"><?php echo $m->getName() ?></a>
                        </li>
                    <?php
                    }
                    ?>
                </ul>
            </div>
        <?php
        }
        ?>
        <div class="clear"></div>
    <?php }
    ?>
</div>