<?php echo $this->getChildHtml('customer.bestseller') ?>
<div class="footer-container">
    <div class="footer">
        <?php //echo $this->getChildHtml() ?>
        <a class="page-up" href="#header">Back to top</a>
        <div class="footer-content">
            <div class="footer-links">
                <div class="links">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links')->toHtml(); ?>
                </div>
                <div class="links">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links_company')->toHtml(); ?>
                </div>
            </div>
            <div class="footer-media">
                <div class="footer-media-wrap">
                    <div class="social-links">
                        <div class="block-title">
                            <strong>
                                <span>Connect with us</span>
                            </strong>
                        </div>
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_social_links')->toHtml(); ?>
                    </div>
                    <div class="newsletter">
                        <span style="display: none" id="subscribe-modal" class="a-link block center">Shipping & Returns</span>
                        <?php echo $this->getChildHtml('newsletter'); ?>
                    </div>
                    <div class="footer-tag">
                        <div class="footer-tag-wrap">
                            <?php echo $this->getChildHtml('footer_tag') ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="bottom_links">
            <div class="bottom_links-inner">
                <address class="copyright"><?php echo $this->getCopyright() ?></address>
                <?php echo $this->getChildHtml('bottom_links'); ?>
            </div>
        </div>
		<div style="height: 45px; width: 100%; border-top: 1px solid #e6e6e6;"></div>
    </div>
</div>
<!-- Footer CSS / JS  -->
<?php echo $this->getCssJsHtml() ?>
<!-- End Footer CSS / JS  -->
<script src="<?php echo $this->getSkinUrl('js/lib/require.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl('build/main.js'); ?>" type="text/javascript"></script> 	
<script language="javascript" type="text/javascript" src="<?php echo $this->getSkinUrl('js/awstats_misc_tracker.js'); ?>" ></script>
<noscript><img src="/js/awstats_misc_tracker.js?nojs=y" height="0" width="0" border="0" style="display: none"></noscript>