<?php
$skin_url = $this->getSkinUrl('', array('_secure'=>true));
$http_host = $_SERVER['HTTP_HOST'];
$session = Mage::getSingleton('core/session');
$SID=$session->getEncryptedSessionId();
$esid = md5($SID);
$hjid = 0;
$fbid = 0;
?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType(); ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<script src="<?php echo $this->helper('core/js')->getJsUrl('mf.js') ?>"></script>
<script src="//plugin.mavrck.co/mavrck_plugin.js" type="text/javascript"></script>
<?php
$url = Mage::helper('core/url')->getHomeUrl();
?>
<script>
	var BASE_URL = '<?php echo $url; ?>';
</script>
<?php
if( $http_host === 'www.purcosmetics.com' || $http_host === 'purcosmetics.com' || $http_host === 'staging.purcosmetics.com' || $http_host === 'development.purcosmetics.com' || $http_host === 'tgi.purcosmetics.com'){
$fbid = '504469726410042';
$hjid = '348334';
?>
<!-- Google structured data -->  
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Organization",
  "url": "https://www.purcosmetics.com",
  "logo":"https://www.purcosmetics.com/media/logos/PurLogo_2015_black.png",
  "name": "Pur Cosmetics",
  "contactPoint": {
    "@type": "ContactPoint",
    "telephone": "+1-678-303-3088",
    "contactType": "Customer service"
  },
  "sameAs": [
    "https://www.facebook.com/PurBeautyCosmetics",
    "https://twitter.com/purcosmetics",
    "https://www.pinterest.com/purcosmetics/",
    "https://www.instagram.com/purcosmetics/",
    "https://www.youtube.com/c/PurCosmetics",
    "https://www.snapchat.com/add/purcosmetics"
  ]  
}
{
  "@context": "http://schema.org",
  "@type": "WebSite",
  "name": "Pur Cosmetics",
  "alternateName": "The Complexion Authority",
  "url": "https://www.purcosmetics.com"
} 
</script>
<!-- End Google structured data -->
<?php 
}
if( $http_host === 'www.cosmedix.com' || $http_host === 'cosmedix.com' || $http_host === 'staging.cosmedix.com' || $http_host === 'development.cosmedix.com' || $http_host === 'tgi.cosmedix.com'){
$fbid = '138843616656556';
$hjid = '515516';
?>  
<!-- Google structured data -->
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Organization",
  "url": "https://www.cosmedix.com",
  "logo":"https://www.cosmedix.com/media/logos/CosMedix_Logo_silver.png",
  "name": "Cosmedix",
  "contactPoint": {
    "@type": "ContactPoint",
    "telephone": "+1-800-676-9522",
    "contactType": "Customer service"
  },
  "sameAs": [
    "https://www.facebook.com/COSMEDIX/",
    "https://twitter.com/CosMedix",
    "https://www.pinterest.com/cosmedix/",
    "https://www.instagram.com/cosmedix_/",
    "https://www.youtube.com/user/CosMedixVideos"
  ]  
}
{
  "@context": "http://schema.org",
  "@type": "WebSite",
  "name": "Cosmedix",
  "alternateName": "Cosmedix",
  "url": "https://www.cosmedix.com"
} 
</script>
<!-- End Google structured data -->
<?php
}
?>
<!-- Hotjar Tracking Code for www.purcosmetics.com -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:<?php echo $hjid; ?>,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
<!-- /Hotjar Tracking Code for www.purcosmetics.com -->
<!-- Facebook Pixel Code -->
<script>!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '<?php echo $fbid; ?>'); 
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" src="https://www.facebook.com/tr?id=<?php echo $fbid; ?>&ev=PageView&noscript=1"/>
</noscript>
<!-- /Facebook Pixel Code -->

<!-- CSS / JS  -->
<?php echo $this->getCssJsHtml() ?>
<!-- End CSS / JS  -->
<!-- TSS -->
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<!-- Inc -->
<?php echo $this->getIncludes() ?>
<!-- Child -->
<?php echo $this->getChildHtml() ?>