<!-- Store mode removal -->
<div class="header-language-background">
    <div class="header-language-container">
        <div class="store-language-container">
        <div class="top-left-message">
            <p class="message"><?php echo $this->getChildHtml('sale-message') ?></p>
        </div>
        <div class="main-message">
            <p class="message"><?php echo $this->getChildHtml('main-message') ?></p>
        </div>
        <?php echo $this->getChildHtml('professional_category') ?>
		</div>
    </div>
</div>
<header id="header" class="page-header">
    <div class="page-header-container">
        <a class="logo" href="<?php echo $this->getUrl('') ?>">
            <span class="PUR_logo_with_slogan"></span>
            <span class="PUR_logo"></span>
        </a>
        <?php // In order for the language switcher to display next to logo on smaller viewports, it will be moved here.
              // See app.js for details ?>
        <!-- Navigation -->
        <div id="header-nav" class="skip-content">
            <div class="skip-content__mobile-title">Menu</div>
            <?php echo $this->getChildHtml('topMenu') ?>
        </div>
        <!-- Skip Links -->
        <div class="skip-links">
            <a href="#header-nav" class="skip-link skip-nav">
                <span class="skip-nav-row"></span>
            </a>

            <div class="account-cart-wrapper">
                <?php echo $this->getChildHtml('login-toggle', false); ?>

            </div>
        </div>
        <!-- Search -->
        <style>
        li.item.odd {
        height: 150px;
        }    
        li.item.even {
        height: 150px;
        }   
        div#minicart-list-block {
        overflow-y: scroll;
        }        
        </style>
        <div id="header-search" class="skip-content form-search-wrap">
            <?php echo $this->getChildHtml('topSearch') ?>
        </div>
        <!-- Cart -->
        <?php echo $this->getChildHtml('minicart_head'); ?>
    </div>
</header>
<div id="ovlem" class="menu-overlay-element"></div>
<?php echo $this->getChildHtml('topContainer'); ?>