
<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
$_bornProductListHelper = Mage::helper('born_package/catalog_product_list');
$_wishlistHelper = Mage::helper('wishlist');
$productUrl = '';
?>
<?php if($this->getItemCount()): ?>
    <div class="crosssell">
        <h2 class="crosssell-title"><?php echo $this->__('More Favorites') ?></h2>
        <ul id="crosssell-products-list" class="products-grid products-grid--max-3-col">
            <?php foreach ($this->getItems() as $_product): ?>
                <li class="item">
                    <div class="item-outer">
                        <div class="item-inner">
                            <div class="item-inner__middle">
                                <?php if ($_product): ?>
                                    <?php 
                                    if(isset($_imgSize)){
                                    $productImages = $_bornProductListHelper->getProductImages($_product, $_imgSize); 
                                    }else{
                                    $productImages = $_bornProductListHelper->getProductImages($_product);
                                    }
                                    ?>
                                    <?php if($_bornProductListHelper->hasColors($_product)) : ?>
                                        <div class="color-swatches">
                                            <dl>
                                                <?php foreach($_bornProductListHelper->getColors($_product) as $color) : ?>
                                                    <dd>
                                                        <a class="<?php echo $color['value_index'] ?>">
                                                        
                                                             
                                                            <?php
                                                            if(array_key_exists('image',$color) && isset($color['image'])){
                                                            echo "<img src=\"".$color['image']."\""; 
								if (array_key_exists('label',$color)&& isset($color['label'])){
								echo "title=\"".$color['label']."\""; 
								}
								if (array_key_exists('product_image',$color)&& isset($color['product_image'])){
								echo "data-product-image=\"".$color['product_image']."\"";
								}
								if (array_key_exists('alt_image',$color)&& isset($color['alt_image'])){
                                                                echo "data-product-alt-image=\"".$color['alt_image']."\"";
								}
                                                            echo " />"; 
                                                            }
                                                            ?>
                                                            
                                                            
                                                        </a>
                                                    </dd>
                                                <?php endforeach; ?>
                                            </dl>
                                            <div class="btns-swatches">
                                                <a class="btn-more" href>More</a>
                                                <a class="btn-less" href>Less</a>
                                            </div>
                                        </div>
                                    <?php endif; ?>

                                    <a href="<?php echo $productUrl ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image alt-img">

                                        <img class="product-image-default" id="product-collection-image-<?php echo $_product->getId(); ?>"
                                        src="<?php echo $productImages['small_image'] ?>"
                                        alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />

                                        <?php if ($productImages['alt_image']) { ?>
                                        <img class="product-image-hover bg" src="<?php echo $productImages['alt_image'] ?>"/>
                                        <?php } else { ?>
                                        <img class="product-image-hover bg" id="product-collection-image-<?php echo $_product->getId(); ?>"
                                        src="<?php echo $productImages['small_image'] ?>"
                                        alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                        <?php } ?>
                                    </a>

                                    <div class="btns">
                                        <a class="quickview" data-coherent-modal data-modal-name="quickview-php" data-modal-id="<?php echo $_product->getId() ?>"><?php echo $this->__('Quick View')?></a>
                                        <a data-formkey="<?php echo $_wishlistHelper->getFormKey() ?>" class="link-wishlist wishlist <?php if($_bornProductListHelper->inWishlist($_product)) echo 'favorite' ?>" href="<?php echo $_wishlistHelper->getAddUrl($_product) ?>"><?php echo $this->__('Favorite')?></a>
                                    </div>
                                    <?php if ($tagMessage = $this->getTagMessage()): ?>
                                        <div class="custom-tag-msg"><?php echo $tagMessage ?></div>
                                    <?php elseif ($_bornProductListHelper->isNewProduct($_product)): ?>
                                        <div class="tag-new"><?php echo $this->__('New') ?></div>
                                    <?php endif ?>

                                    <div class="product-info">
                                        <h2 class="product-name"><a href="<?php echo $productUrl ?>" title="<?php echo $_product->getName()?>"><?php echo $_product->getName() ?></a></h2>
                                        <?php if ($_subText = Mage::helper('born_package/catalog_product_list')->getSubText($_product)): ?>
                                            <p class="product-subtitle"><?php echo $_subText ?></p>
                                        <?php endif ?>
                                        <?php $priceHtml = $this->getPriceHtml($_product) ?>
                                        <?php echo $priceHtml ?>
                                    </div>
                                <?php else: ?>
                                    <div class="product-not-found">
                                        <h2><?php echo $this->__('Product Not Found') ?></h2>
                                        <?php if ($_productSku): ?>
                                            <h2><?php echo $this->__('SKU') . ': ' . $_productSku ?></h2>
                                        <?php else: ?>
                                            <p><?php echo $this->__('No SKU Defined.') ?></p>
                                        <?php endif ?>
                                        <p></p>
                                    </div>
                                <?php endif ?>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
        <?php // <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script> ?>
    </div>
<?php endif; ?>
