<div id="orderAddhandling" class="entry-edit clear">
     <h5><?php echo Mage::helper('sales')->__('Can be left blank if handling fee is not applicable') ?></h5>
     <div class="content">
         <label for="fee_amount">Handling Fee</label>
         <span><input id="handling_fee" name="fee_amount" type="text" class="validate-not-negative-number input-text" style="width:200px" >  </span>
     </div>
</div>