<!-- <?php echo __FILE__; ?> -->
<?php
        if (isset($_SERVER['MAGE_IS_DEVELOPER_MODE'])) { 
        //Mage::log(__METHOD__, false, 'OptionSwatch.log');
        }
    $_groupedProductCollection = $this->groupProducts();
    $_helper = $this->helper('catalog/output');
    $_bornProductListHelper = Mage::helper('born_package/catalog_product_list');
    $_category = $this->getLayer()->getCurrentCategory();

?> 

<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>

    <?php foreach($_groupedProductCollection as $categoryId => $_groupedProduct) : ?>
        
        <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
            <?php $i = 1 ?>
               <?php if (count($categoryId)): ?>
                    <li class="item item-category-title first" style="background-image: url(<?php echo Mage::getBaseUrl('media').'catalog/category/' . $categoryImage  ?>)">
                        <div class="item-outer">
                            <div class="item-inner">
                                <div class="item-inner__middle">
                                <?php $pageContainsProducts = true; ?>
                                <?php $category = $this->getCategoryById($categoryId) ?>
                                <?php if ($categoryImage = $category->getData('image')): ?>
                                     <div class="background-img-div" style="background-image: url(<?php echo Mage::getBaseUrl('media').'catalog/category/' . $categoryImage  ?>)"></div>
                                <?php endif ?>
                                <?php if ($category->getName()): ?>
                                    <h2 class="category-title"> <?php echo $category->getName() ?></h2>
                                <?php endif ?>
                                <?php if (count($_groupedProduct)): ?>
                                    <p class="product-count"><?php echo count($_groupedProduct) . ' ' . $this->__('Products')?></p>
                                <?php endif ?>
                                <?php if ($category->getDescription() ): ?>
                                    <h4 class="category-description"><?php echo $category->getDescription() ?></h4>
                                <?php endif ?>
                                <?php $i++; ?>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endif ?>

            <?php foreach($_groupedProduct as $_product) : ?>
                <?php /*if ($i++%$_columnCount==0): ?>
                <?php endif*/ ?>
                <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                    <div class="item-outer">
                        <div class="item-inner">
                            <div class="item-inner__middle">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image alt-img">
                                    <?php $_imgSize = 210; ?>

                                    <?php $productImages = $_bornProductListHelper->getProductImages($_product, $_imgSize) ?>

                                    <img class="product-image-default" id="product-collection-image-<?php echo $_product->getId(); ?>"
                                         src="<?php echo $productImages['small_image'] ?>"
                                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />

                                    <?php if ($productImages['alt_image']) { ?>
                                        <img class="product-image-hover bg" src="<?php echo $productImages['alt_image'] ?>"/>
                                    <?php } else { ?>
                                        <img class="product-image-hover bg" id="product-collection-image-<?php echo $_product->getId(); ?>"
                                             src="<?php echo $productImages['small_image'] ?>"
                                             alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                    <?php } ?>

                                </a>

                                <div class="btns">
                                    <a class="quickview" data-coherent-modal data-modal-name="quickview-php" data-modal-id="<?php echo $_product->getId() ?>"><?php echo $this->__('Quick View')?></a>
                                    <a class="wishlist" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Favorite')?></a>
                                </div>

                                <div class="product-info">
                                    <?php if ($_bornProductListHelper->isNewProduct($_product)): ?>
                                        <div class="tag-new"><?php echo $this->__('New') ?></div>
                                    <?php endif ?>
                                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                                    <?php
                                    // Provides extra blocks on which to hang some features for products in the list
                                    // Features providing UI elements targeting this block will display directly below the product name
                                    if ($this->getChild('name.after')) {
                                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                        foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                            $_nameAfterChild->setProduct($_product);
                                            echo $_nameAfterChild->toHtml();
                                        }
                                    }
                                    ?>
                                    <?php echo $this->getPriceHtml($_product, true) ?>
                                    <?php if($_product->getRatingSummary()): ?>
                                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <?php /*if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
                <?php endif*/ ?>
                <?php $i++ ?>
            <?php endforeach ?>
        </ul>
    <?php endforeach ?>

    <?php if (!$pageContainsProducts): ?>
        <h1 class="no-results"><?php echo $_category->getName(); ?></h1>
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php endif ?>

    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    
</div>

<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>
<!-- <?php echo __FILE__; ?> -->