<?php
/**
 * Magento Enterprise Edition
 *
 * @category    design
 * @package     cleo_purcosmetics
 */
?>
<?php $_order = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId()); ?>
<!-- Event snippet for Pur Minerals Purchase conversion page -->
<script>
  gtag('event', 'conversion', {
      'send_to': 'AW-1059501670/WGZdCLKeRhDm7Jr5Aw',
      'value': '<?php echo number_format($_order->getGrandTotal(), 2); ?>',
      'currency': 'USD',
      'transaction_id': '<?php echo $this->getOrderId(); ?>'
  });
</script>
<div class="checkout-success-wrapper">
    <div class="page-title">
        <h1><?php echo $this->__('Your order has been received.') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h2>

    <?php if ($this->getOrderId()):?>
    <?php if ($this->getCanViewOrder()) :?>
        <p><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></p>
    <?php  else :?>
        <p><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?></p>
    <?php endif;?>
        <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
    <?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
        <p>
            <?php echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $this->getPrintUrl()) ?>
            <?php echo $this->getChildHtml() ?>
        </p>
    <?php endif;?>
    <?php endif;?>

    <?php if ($this->getAgreementRefId()): ?>
        <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
    <?php endif;?>

    <?php if ($profiles = $this->getRecurringProfiles()):?>
    <p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
    <ul class="disc">
    <?php foreach($profiles as $profile):?>
    <?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
        <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
    <?php endforeach;?>
    </ul>
    <?php endif;?>
</div>

