<style>
p.price-as-configured {
    display: none;
}
</style>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php $_bornHelper = Mage::helper('born_package'); ?>

<h2><?php echo $this->__('The Highlights'); ?></h2>
<div class="hightlights-wrap">
    <div class="hightlights-side">
        <div class="hightlights-side-inner">
            <div class="description">
				<?php $type = array('bundle','grouped'); 
				$description = $_product->getDescription();
				$highlight = $_product->getProductHighlights();
				?>
				<?php 
				if(!in_array($_product->getTypeId(),$type)){
					if(isset($description)&&!empty($description)){
					echo $_product->getDescription();	
					}
					if(isset($highlight)&&!empty($highlight)){
					echo $_product->getProductHighlights();	
					}					
				}else{ 
					if(isset($description)&&!empty($description)){
					echo $_product->getDescription();	
					}
					if(isset($highlight)&&!empty($highlight)){
					echo $_product->getProductHighlights();	
					}				 
				} 
				?>
            </div>
        </div>
    </div>
    <?php if($_product->getData('highlight_video_image') && $_product->getData('highlight_video_image') != 'no_selection') : ?>
        <div class="hightlights-side">
        <?php if ($_product->getHighlightVideoLink()): ?>            
            <div class="video" data-link="<?php echo $_product->getHighlightVideoLink(); ?>">
                <div class="title"><?php echo $_product->getName() ?></div>
                <img class="alt yt-video-bg" src="<?php echo $_bornHelper->getImageUrl($_product, 'highlight_video_image') ?>" width="" height="" alt="<?php $this->stripTags($_product->getName(), null, true) ?>" />

                <?php $_youtubeId = $_bornHelper->getYoutubeId($_product->getHighlightVideoLink()); ?>
                <iframe class="yt-video" width="100%" height="350px" src="https://www.youtube.com/embed/<?php $_youtubeId ?>"
                data-autoplay-src="https://www.youtube.com/embed/<?php echo $_youtubeId ?>?autoplay=1&showinfo=0&controls=0" frameborder="0" allowfullscreen></iframe>

                <p class="image-label yt-video-starter"><?php echo $_product->getName() ?></p>
            </div>
        <?php else: ?>
            <div class="image">
                <img class="highlight-image" src="<?php echo $_bornHelper->getImageUrl($_product, 'highlight_video_image') ?>" width="" height="" alt="<?php $this->stripTags($_product->getName(), null, true) ?>" />
            </div>
        <?php endif ?>
        </div>
    <?php endif; ?>
</div>