<?php
        if (isset($_SERVER['MAGE_IS_DEVELOPER_MODE'])) { 
        //Mage::log(__METHOD__, false, 'OptionSwatch.log');
        }
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<ul class="tabs">
    <li class="active" rel="tab1"><span><?php echo $this->__('Application'); ?></span></li>
    <?php if ($this->getBenefits()): ?>
            <li rel="tab2"><span><?php echo $this->__('Benefits'); ?></span></li>
    <?php endif ?>

    <?php if ($_product->getIngredients()): ?>
            <li rel="tab3"><span><?php echo $this->__('Ingredients'); ?></span></li>
    <?php endif ?>

</ul>
<div class="tab-container">
    <h3 class="tab-drawer-heading" rel="tab1"><?php echo $this->__('Application'); ?></h3>
    <div id="tab-application" class="tab-content tab1 application">
        <div class="directions-container">

            <?php if (($_product->getData('directions_image') && $_product->getData('directions_image') != 'no_selection') || $_product->getDirectionsSku()): ?>
                <div class="directions">
            <?php else: ?>
                <div class="directions no-complimentary-tool">
            <?php endif ?>
                <div class="directions-outer">
                    <div class="directions-inner">
                        <?php echo $_product->getDirections(); ?>
                    </div>
                </div>
            </div>

            <?php if ($_product->getData('directions_image') && $_product->getData('directions_image') != 'no_selection'): ?>
                <div class="directions-image">
                    <div class="directions-image-outer">
                        <div class="directions-image-inner">
                            <img class="alt" src="<?php echo $this->helper('catalog/image')->init($_product, 'directions_image'); ?>" width="" height="" />
                        </div>
                    </div>
                </div>
            <?php elseif($productTool = Mage::getModel('catalog/product')->loadByAttribute('sku', $_product->getDirectionsSku())) : ?>
                <div class="product-tool">
                    <div class="product-tool-outer">
                        <div class="product-tool-inner">
                            <a href="<?php echo $this->getUrl($productTool->getUrlKey()) ?>" title="<?php echo $productTool->getName(); ?>">
                                <?php if ($_product->getTagText()): ?>
                                    <span class="eclipse"><?php echo $_product->getTagText(); ?></span>
                                <?php endif ?>
                                <img class="alt" src="<?php echo $this->helper('catalog/image')->init($productTool, 'thumbnail'); ?>" width="" height="" alt="<?php $this->stripTags($productTool->getName(), null, true) ?>" />
                                <p><?php echo $productTool->getName(); ?></p>
                                <span><?php echo $this->getPriceHtml($productTool); ?></span>
                            </a>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>

        <?php if($_product->getProTip() && $_product->getData('pro_tip_image') && $_product->getData('pro_tip_image') != 'no_selection') : ?>
            <div class="pro-tip-container">
                <div class="pro-tip" >
                    <div class="pro-tip__outer">
                        <div class="pro-tip__image" style="background-image: url(<?php echo $this->helper('catalog/image')->init($_product, 'pro_tip_image'); ?>)"></div>
                    </div>
                </div>
                <div class="pro-tip">
                    <div class="pro-tip__outer">
                        <div class="pro-tip__inner">
                            <?php echo $_product->getProTip(); ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <?php if ($this->getDisplayHowTo($_product)): ?>
            
            <div class="how-to-container">
                <h2 class="how-to-container-title"><?php echo $_product->getHowToMainTitle(); ?></h2>

                <div class="how-to-container__col-wrap">
                <?php if($_product->getData('how_to_image1') && $_product->getData('how_to_image1') != 'no_selection') : ?>
                    <div class="how-to-card">
                        <div class="front" style="background-image: url(<?php echo $this->helper('catalog/image')->init($_product, 'how_to_image1'); ?>)">
                            <?php if ($howToTitle1 = $_product->getData('how_to_title1')): ?>
								<?php $title1 = explode('||',$howToTitle1); ?>
                                <div class="how-to-card-block-title"><?php echo $title1[0] ?></div>
                            <?php endif ?>
                            <?php if ($_product->getHowToInstructions1()): ?>
                                <span class="how-to-card__eye <?php if(array_key_exists(1,$title1) && $title1[1]=='black'){ echo 'how-to_black'; }else{ echo 'how-to_white'; } ?>">
								<?php echo $_product->getHowToText1() ?><i class="eye icon turn-to-back"></i></span>
                            <?php endif ?>
                        </div>
                        <?php if ($_product->getHowToInstructions1()): ?>
                             <div class="back">
                                 <?php echo $this->processCmsHtml($_product->getHowToInstructions1()); ?>
                                 <i class="how-to-card__close-eye close-eye icon turn-to-front"></i>
                             </div>
                        <?php endif ?>
                    </div>
                <?php endif; ?>

                <?php if($_product->getData('how_to_image2') && $_product->getData('how_to_image2') != 'no_selection') : ?>
                    <div class="how-to-card">
                        <div class="front" style="background-image: url(<?php echo $this->helper('catalog/image')->init($_product, 'how_to_image2'); ?>)">
                            <?php if ($howToTitle2 = $_product->getData('how_to_title2')): ?>
								<?php 
								$title2 = explode('||',$howToTitle2);
								
								?>
                                <div class="how-to-card-block-title"><?php echo $title2[0] ?></div>
                            <?php endif ?>
                            <?php if ($_product->getHowToInstructions2()): ?>
                                <span class="how-to-card__eye <?php if(isset($title2) && array_key_exists(1,$title2) && $title1[1]=='black'){ echo 'how-to_black'; }else{ echo 'how-to_white'; } ?>">
								<?php echo $_product->getHowToText2() ?><i class="eye icon"></i></span>
                            <?php endif ?>
                        </div>
                        <?php if ($_product->getHowToInstructions2()): ?>
                            <div class="back">
                                <?php echo $this->processCmsHtml($_product->getHowToInstructions2()); ?>
                                <i class="how-to-card__close-eye close-eye icon turn-to-front"></i>
                            </div>
                        <?php endif ?>
                    </div>
                <?php endif; ?>
                </div>
            </div>
    <?php endif ?>
    </div>
    <?php $benefits = $this->getBenefits(); ?>
    <?php if ($benefits): ?>
        <h3 class="tab-drawer-heading" rel="tab2"><?php echo $this->__('Benefits'); ?></h3>
        <div id="tab-benefits" class="tab-content tab2 benefits">
            <?php foreach($benefits as $benefit) : ?>
                <div class="benefit">
                    <div class="benefit-outer">
                        <div class="benefit-inner">
                            <div class="benefit-inner-middle">
                                <?php if (strpos($benefit['image'], '.svg')): ?>
                                    <img class="benefit-img svg-file" src="<?php echo $benefit['image']; ?>" width="45px"/>
                                <?php else: ?>
                                    <img class="benefit-img non-svg-file" src="<?php echo $benefit['image']; ?>"/>
                                <?php endif ?>
                                <p class="benefit-description"><?php echo $benefit['description']; ?></p>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif ?>
    <?php if ($_product->getIngredients()): ?>
       <h3 class="tab-drawer-heading" rel="tab3"><?php echo $this->__('Ingredients'); ?></h3>
       <div id="tab-ingredients" class="tab-content tab3 ingredients">
            <h2><?php echo $this->__('All Ingredients') ?></h2>
            <p><?php echo $_product->getIngredients(); ?></p>
        </div>
    <?php endif ?>   
</div>
</div>