<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Perm
 */
?>
<?php

$dealer = $this->getDealer();
if ($dealer->getId() && $dealer->getDescription()): ?>
<div class="block">
	<div class="block-title">
    	<strong><span><?php echo $this->__('Your Dealer Info') ?></span></strong>
    </div>
    <div class="block-content">
    	<div class="empty"><?php echo Mage::helper('cms')->getBlockTemplateProcessor()->filter($dealer->getDescription());?></div>
	</div>
</div>
<?php endif;?>
