<?php
	$id_path = explode('product', $this->getIdPath());
	$productId = end($id_path);
    $productId = trim($productId, '/');
	// Trim a array?
    //$productId = trim(end(explode('product', $this->getIdPath())), '/');
    $_product = Mage::getModel('catalog/product')->load($productId);
    $_helper = $this->helper('catalog/output');
    $_customHelper = $this->helper('weltpixel_custom');
if ($_product): 
    $_settings = Mage::getStoreConfig('weltpixel_selector/categoryoptions');
    $_productNameStripped = $this->stripTags($_product->getName(), null, true);
    $_productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
    $_productAddToCart = $this->getAddToCartUrl($_product);
    //$_productAddToCart = Mage::helper('checkout/cart')->getAddUrl($_product);
    $_addToCartLightBox = ('lightbox' == $_settings['addtocartbutton']);
    $_wishlistIsAllow = $this->helper('wishlist')->isAllow();
    $_wishlistUrl = $this->helper('wishlist')->getAddUrl($_product);
    $_hoverShowName = (Mage::getStoreConfig('weltpixel_selector/categoryoptions/showname') == "yes");
    $_shortTitle = (Mage::getStoreConfig('weltpixel_selector/categoryoptions/onelinetitle') == "yes");
    $_showAddToCart = ('yes' == $_settings['addtocart']);
    $_showAddToWishlist = ('yes' == $_settings['addtowishlist']);
    $_showAddToCompare = ('yes' == $_settings['addtocompare']);
    $_showAddToBox = $_showAddToCart || $_showAddToWishlist || $_showAddToCompare;
    $_showQuickView = ('yes' == $_settings['enablequickview']);
    $_disableBackImage = Mage::getStoreConfig('weltpixel_selector/categoryoptions/disable_back_image');
    $_useRetina = Mage::getStoreConfig('weltpixel_selector/customization_settings/retina');
    $_imgSize = 375;
    $_imgSizeRetina = 2 * $_imgSize;
    //hover image preparation
    $_secondImage = '';
    $_secondImageRetina = '';

    if (!$_disableBackImage) {
        $_resource = Mage::getModel('catalog/product')->getResource();
        $altImage = $_resource->getAttributeRawValue($_product->getId(), 'alt_image', Mage::app()->getStore());
        if ($altImage) {
            $_secondImage = (string) $this->helper('catalog/image')
                ->init($_product, 'alt_image', $altImage)
                ->constrainOnly(true)
                ->keepAspectRatio(true)
                ->keepFrame(true)
                ->resize($_imgSize)
            ;

            if ($_useRetina) {
                $_secondImageRetina = (string) $this->helper('catalog/image')
                    ->init($_product, 'alt_image', $altImage)
                    ->constrainOnly(true)
                    ->keepAspectRatio(true)
                    ->keepFrame(true)
                    ->resize($_imgSizeRetina)
                ;
            }
        }
    }

    // product main image
    $_productImage = (string) $this->helper('catalog/image')
        ->init($_product, 'thumbnail')->constrainOnly(true)->keepAspectRatio(true)->keepFrame(false)->resize($_imgSize);
    $_productImageRetina = '';
    if ($_useRetina) {
        $_productImageRetina = (string) $this->helper('catalog/image')
            ->init($_product, 'small_image')->constrainOnly(true)->keepAspectRatio(true)->keepFrame(false)->resize($_imgSizeRetina);
    }

    ?>
    <div class="product-widget category-products-widget">
        <ul class="products-grid">
            <li>
                <div class="item">
                    <?php $noHover = 'no-hover'; ?>
                    <?php if (!$_disableBackImage && $_secondImage != '')  : ?>
                        <?php $noHover = ''; ?>
                        <a
                            href="<?php echo $_product->getProductUrl() ?>"
                            title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                            class="hover product-image">
                            <img
                                id="widget-product-collection-image-<?php echo $_product->getId(); ?>"
                                src="<?php echo $_secondImage; ?>"
                                data-src="<?php echo $_secondImage; ?>"
                                <?php if ($_useRetina): ?>
                                    data-src-retina="<?php echo $_secondImageRetina; ?>"
                                <?php endif; ?>
                                alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                            />
                        </a>
                    <?php endif; ?>
                    <a
                        href="<?php echo $_product->getProductUrl() ?>"
                        title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                        class="default product-image <?php echo $noHover; ?> ">
                        <img
                            <?php if ($_disableBackImage) : ?>
                                id="product-collection-image-<?php echo $_product->getId(); ?>"
                            <?php endif; ?>
                            src="<?php echo $_productImage; ?>"
                            <?php if ($_useRetina): ?>
                                data-src-retina="<?php echo $_productImageRetina; ?>"
                            <?php endif; ?>
                            alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                        />
                    </a>
                    <div class="item-info">
                        <span class="<?php echo($_hoverShowName) ? "show" : "hide"; ?>">
                            <a
                                href="<?php echo $_product->getProductUrl(); ?>"
                                title="<?php echo $_productNameStripped; ?>"
                                class="product-title <?php echo($_shortTitle) ? "shortTitle" : "longTitle"; ?>"
                            >
                                <?php echo $_productName; ?>
                            </a>
                        </span>

                        <?php if ($_showAddToBox): ?>
                            <div class="add-to-box">
                                <table>
                                    <tr>
                                        <?php if ($_product->isSaleable() && $_showAddToCart): ?>
                                            <td>
                                                <?php if (($_productUrl == $_productAddToCart) && $_addToCartLightBox): ?>
                                                    <a
                                                        href="javascript: void(0);"
                                                        onclick="weltpixel.quickview.showProductInfoModal('<?php echo $this->getQuickViewUrl($_product); ?>');"
                                                        class="add-to-cart">
                                                        <span>
                                                            <i class="icon icon-shopping-cart"></i>
                                                            <?php echo $this->__('Add to Cart'); ?>
                                                        </span>
                                                    </a>
                                                <?php else: ?>
                                                    <a
                                                        href="<?php echo $_productAddToCart; ?>"
                                                        class="add-to-cart">
                                                        <span>
                                                            <i class="icon icon-shopping-cart"></i>
                                                            <?php echo $this->__('Add to Cart'); ?>
                                                        </span>
                                                    </a>
                                                <?php endif; ?>
                                            </td>
                                        <?php endif; ?>
                                        <?php if ($_wishlistIsAllow && $_showAddToWishlist) : ?>
                                            <td>
                                                <a class="wishlist" href="<?php echo $_wishlistUrl; ?>">
                                                    <i class="icon icon-line-heart"></i>
                                                    <?php echo $this->__('Favorite') ?>
                                                </a>
                                            </td>
                                        <?php endif; ?>
                                    </tr>
                                </table>
                            </div>
                        <?php endif; ?>
                        <?php if ($_showQuickView): ?>
                            <?php if (Mage::getStoreConfig('weltpixel_selector/categoryoptions/quickview_design') == 'version1'): ?>
                                <a
                                    href="javascript: void(0);"
                                    onclick="weltpixel.quickview.showProductInfoModal('<?php echo $_customHelper->getQuickViewUrl($_product); ?>');"
                                    class="quickview">
                                    <i class="icon-eye-open"></i>
                                    <?php echo $this->__('Quickview'); ?>
                                </a>
                            <?php elseif (Mage::getStoreConfig('weltpixel_selector/categoryoptions/quickview_design') == 'version2'): ?>
                                <a
                                    href="javascript: void(0);"
                                    onclick="weltpixel.quickview.showProductInfoInline('<?php echo $_customHelper->getQuickViewUrl($_product); ?>', this);"
                                    class="quickview">
                                    <i class="icon-eye-open"></i>
                                    <?php echo $this->__('Quickview'); ?>
                                </a>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                </div>
            </li>
        </ul>
    </div>
<?php endif; ?>