
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php
$routes[0] = Mage::app()->getRequest()->getRouteName();
$routes[1] = Mage::app()->getRequest()->getControllerName();
$routes[2] = Mage::app()->getRequest()->getActionName();
$fullAction = implode('/', $routes);
$varienFormId = ($fullAction == 'bornajax/catalog_product/quickviewblock') ? 'product_addtocart_form_' . $_product->getId() : 'product_addtocart_form';
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);

	function shwhdr(pv){
document.getElementById("prodrv").style.display = (pv=="1") ? "block" : "none";
	}

//document.getElementById("prodrv").style.display = "inline";
</script>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
        <form class="form-add-to-cart"
              action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>"
              method="post"
              id="<?php echo $varienFormId ?>"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>"/>
                <input type="hidden" name="related_product" id="related-products-field" value=""/>
            </div>

            <div class="form-add-to-cart-row">
                <div class="product-img-box">
                    <div class="product-name">
                        <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                    </div>
                    <?php echo $this->getChildHtml('media') ?>
                </div>

                <div class="product-shop">
                    <div class="product-name">
                        <h2><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            <?php if ($_product->getUsage()): ?>
                                <?php if ($_usageIconClass = Mage::helper('born_package/catalog_product_data')->getUsageIconClass($_product->getUsage())): ?>
                                    <div class="usage-icon">
                                        <?php //usage icon class names: am-icon, pm-icon, ampm-icon ?>
                                        <span class="<?php echo $_usageIconClass ?>"><span class="path1"></span><span
                                                class="path2"></span><span class="path3"></span><span
                                                class="path4"></span><span class="path5"></span></span>
                                    </div>
                                <?php endif ?>
                            <?php endif ?>
                        </h2>
                        <h4><?php echo $_product->getSubtitle(); ?></h4>
                        <?php echo $this->getChildHtml('group-description') ?>


                    </div>

                    <?php //echo $this->getChildHtml('shade_swatch') ?>

                    <?php if ($_shadeGuide = $this->getShadeGuideHtml()): ?>
                        <div id="shade-guide-url" style="display: none">
                            <?php echo $_shadeGuide ?>
                        </div>
                    <?php endif ?>

                    <div class="price-info">
                        <?php echo $this->getPriceHtml($_product,true); ?>
                        <?php echo $this->getChildHtml('bundle_prices') ?>
                        <?php echo $this->getTierPriceHtml() ?>

                        <?php echo $this->getChildHtml('tier_pricing') ?>
                    </div>

                    <div class="extra-info">
                        <?php  echo $this->getReviewsSummaryHtml($_product, 'default', false); ?>
                        <?php echo $this->getChildHtml('product_type_availability'); ?>
                    </div>

                    <?php echo $this->getChildHtml('alert_urls') ?>

                    <?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE): ?>
                        <div class="data-table-item">
                            <div class="data-table-item-shade"></div>
                        </div>
                    <?php endif; ?>

                    <?php echo $this->getChildHtml('other'); ?>

                    <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                        <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                    <?php endif; ?>
                    <?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_GROUPED): ?>
                    <!-- Possible hack for grouped product nested forms because xHTML not allowing to include one form in to another.  -->
        </form>
        <?php endif; ?>
        <div class="add-to-cart-wrapper">
            <?php echo $this->getChildHtml('product_type_data') ?>
            <?php echo $this->getChildHtml('extrahint') ?>

            <?php if (!$this->hasOptions()): ?>
                <div class="add-to-box">
                    <?php if ($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        <?php if ($this->helper('wishlist')->isAllow() || $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                            <span class="or"><?php echo $this->__('OR') ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('addto') ?>
                    <?php echo $this->getChildHtml('sharing') ?>
                </div>
                <?php echo $this->getChildHtml('extra_buttons') ?>
            <?php elseif (!$_product->isSaleable()): ?>
                <div class="add-to-box">
                    <?php echo $this->getChildHtml('addto') ?>
                    <?php echo $this->getChildHtml('sharing') ?>
                </div>
            <?php endif; ?>
        </div>

        <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif; ?>
        <div class="configurable-alert-block" style="display: none;">

        </div>
    </div>
</div>
<?php if ($_product->getTypeId() != Mage_Catalog_Model_Product_Type::TYPE_GROUPED): ?>
        </form>
        <?php endif; ?>
<script type="text/javascript">
    //<![CDATA[
    //TODO: replace with ajax

    var productAddToCartForm = new VarienForm('<?php echo $varienFormId ?>');
    productAddToCartForm.submit = function (button, url) {
        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;

            if (url) {
                form.action = url;
            }
            var e = null;
            try {
                //this.form.submit();
                // Fix for postUrl based on page protocol
                <?php if (Mage::app()->getStore()->isFrontUrlSecure() && Mage::app()->getRequest()->isSecure()) { ?>
                var postUrl = '<?php echo Mage::getUrl('bornajax/checkout_cart/add/', array('_secure'=>true) ); ?>';
                <?php }else { ?>
                var postUrl = '<?php echo Mage::getUrl('bornajax/checkout_cart/add/'); ?>';
                <?php } ?>

                $j.post(postUrl, $('<?php echo $varienFormId ?>').serialize(true), function (data, status, xhr) {
                    if (status !== 'success') {
                        alert('server error');
                        return;
                    }

                    var json = $j.parseJSON(data);
                    var timeForMinicart = 400; //ms
                    var popup = $j('#popup-minicart');

                    if (json.status === "SUCCESS" || json.status === 1 || json.success) {
                        $j('#toggleMiniCartBtn').find('.count').html(json.cart_qty);
                        $j('#toggleMiniCartBtn').removeClass('no-count');
                        $j('.show-on-mobile.skip-cart').find('.count').html(json.cart_qty);
                        $j('.show-on-mobile.skip-cart').removeClass('no-count');
                        if (window.innerWidth > 768) {
                            $j('#popup-minicart').html(json.result_html);
                            $j('.overlay').fadeOut('slow');
                            $j('.overlay').find('.modal').hide();
                            popup.addClass('slide-minicart').css('display', 'block')
                                .addClass('skip-active')
                                .animate({'right': 0}, timeForMinicart);
                            $j('body').css('overflow', 'scroll');
                            $j('body').addClass('overlay-menu');

                            $j('.menu-overlay-element, span.btn-minicart-toggle').on('click', function () {
                                popup.animate({"right": "-425"}, timeForMinicart,
                                    function () {
                                        popup.removeClass('skip-active');
                                        $j('body').removeClass('overlay-menu');
                                    });
                            });
                        } else {
                            $j(button).addClass('added-successfully');
                            $j(button).find('span').text('added to bag');
                        }
                        button.disabled = false;
                    } else {
                        alert(json.message);
                        button.disabled = false;
                    }
                });
            } catch (e) {
            }
            this.form.action = oldUrl;
            if (e) {
                throw e;
            }

            if (button && button != 'undefined') {
                button.disabled = true;
            }
        }
    }.bind(productAddToCartForm);

    productAddToCartForm.submitLight = function (button, url) {
        if (this.validator) {
            var nv = Validation.methods;
            delete Validation.methods['required-entry'];
            delete Validation.methods['validate-one-required'];
            delete Validation.methods['validate-one-required-by-name'];
            // Remove custom datetime validators
            for (var methodName in Validation.methods) {
                if (methodName.match(/^validate-datetime-.*/i)) {
                    delete Validation.methods[methodName];
                }
            }

            if (this.validator.validate()) {
                if (url) {
                    this.form.action = url;
                }
                this.form.submit();
            }
            Object.extend(Validation.methods, nv);
        }
    }.bind(productAddToCartForm);
    //]]>
</script>
</div>

<?php if ($this->getShowCmsContents()): ?>
    <?php echo $this->getChildHtml('product.custom.content'); ?>
<?php endif ?>
<?php if ($_product->getRoutineSkus()): ?>
    <?php echo $this->getChildHtml('routines') ?>
<?php else: ?>
</div>
            <?php echo $this->getChildHtml('related_products'); ?>
<?php endif ?>

<div><?php echo $this->getChildHtml('product_review') ?></div>
</div>
