<!-- <?php echo __FILE__; ?> -->
<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$_bornProductListHelper = Mage::helper('born_package/catalog_product_list');
$_category = $this->getLayer()->getCurrentCategory();
$catData = $_category->getData();
$storeId = Mage::app()->getStore()->getId();
    if($storeId == 1){
       $affiliation = 'Pur Cosmetics'; 
    }else if($storeId == 2){
        $affiliation = 'Cosmedix';
    }else if($storeId == 3){
        $affiliation = 'Cosmedix';
    }else{
        $affiliation = '';
    }
    if(!$_productCollection->count()): 
?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products default">
<?php 
echo $this->getToolbarHtml();
    if($this->getMode()!='grid'):  
    $_iterator = 0; 
?>
    <ol class="products-list" id="products-list">
<?php 
        foreach ($_productCollection as $_product):
?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
                        one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
                        we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
                        will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                        This $_imgSize value could even be decreased further, based on the page layout
                        (one column, two column, three column) and number of product columns. */ ?>
                <?php $_imgSize = 300; ?>
                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            </a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <div class="product-primary">
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                        <?php if($_product->getRatingSummary()): ?>
<?php echo $this->getReviewsSummaryHtml($_product, false, true) ?>
                       
                        <?php endif; ?>
                        <?php
                        // Provides extra blocks on which to hang some features for products in the list
                        // Features providing UI elements targeting this block will display directly below the product name
                        if ($this->getChild('name.after')) {
                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                            foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                $_nameAfterChild->setProduct($_product);
                                echo $_nameAfterChild->toHtml();
                            }
                        }
                        ?>
                    </div>
                    <div class="product-secondary">
                        <?php echo $this->getPriceHtml($_product, true) ?>
                    </div>
                    <div class="product-secondary">
                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                            <p class="action"><button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Bag')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Bag') ?></span></span></button></p>
                        <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                            <p class="action"><a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
                        <?php else: ?>
                            <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>


    <?php // Grid Mode ?>


    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>

    <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
            <?php $i = 1 ?>
            <?php if ($_productCollection->count()): ?>
                <li class="item item-category-title first">
                    <div class="item-outer<?php if (!$_category->getData('image')): ?> no-bg<?php endif ?>">
                        <div class="item-inner">
                            <div class="item-inner__middle">
                                <?php $pageContainsProducts = true; ?>
                                <?php if ($categoryImage = $_category->getData('image')): ?>
                                    <div class="background-img-div" style="background-image: url(<?php echo Mage::getBaseUrl('media').'catalog/category/' . $categoryImage  ?>)"></div>
                                    <div class="background-arrow"></div>
                                <?php endif ?>
                                <?php if ($_category->getName()): ?>
                                    <h2 class="category-title"> <?php echo $_category->getName() ?></h2>
                                <?php endif ?>
                                <p class="product-count"><?php echo $_productCollection->count() . ' ' . $this->__('Products')?></p>
                                <?php if ($_category->getDescription()): ?>
                                    <h4 class="category-description"><?php echo $_category->getDescription() ?></h4>
                                <?php endif ?>
                                <?php $i++; ?>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endif ?>

            <?php 
            $productArray = array();
            $pc = 1;
                foreach ($_productCollection as $_product):
                $product_item = array();
                $product_item['sku'] = $_product->getSku();
                $product_item['name'] = $_product->getName();
                $product_item['brand'] = $affiliation;
                $product_item['position'] = $pc;
                $pc++;
                $_filterColor = null; 
                ?>
                <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                    <div class="item-outer">
                        <div class="item-inner">
                            <div class="item-inner__middle">
                            <?php if($_bornProductListHelper->hasColors($_product)) : ?>
                                <div class="color-swatches">
                                    <dl>
                                    <?php $_swatchActiveSet = false; //Ensure that only one swatch will be active at a time. ?>
                                    <?php foreach($_bornProductListHelper->getColors($_product) as $color) : ?>
                                        <dd>
                                        <?php $_isSwatchActive = $this->isSwatchActive($color['value_index']) ?>
                                        <?php if ($_swatchActiveSet && $_isSwatchActive): ?>
                                            <?php $_isSwatchActive = false; ?>
                                        <?php elseif (!$_swatchActiveSet && $_isSwatchActive): ?>
                                            <?php $_filterColor = $color ?>
                                            <?php $_swatchActiveSet = true; ?>
                                        <?php endif ?>
                                        <a class="<?php echo $color['value_index'] ?>  <?php echo $_isSwatchActive ? 'active-swatch' : '' ?>" >
                                                            <?php
                                                            if(array_key_exists('image',$color) && isset($color['image'])){
                                                            echo "<img src=\"".$color['image']."\""; 
								if (array_key_exists('label',$color)&& isset($color['label'])){
								echo "title=\"".$color['label']."\""; 
								}
								if (array_key_exists('product_image',$color)&& isset($color['product_image'])){
								echo "data-product-image=\"".$color['product_image']."\"";
								}
								if (array_key_exists('alt_image',$color)&& isset($color['alt_image'])){
                                                                echo "data-product-alt-image=\"".$color['alt_image']."\"";
								}
                                                            echo " />"; 
                                                            }
                                                            ?>

                                            </a>
                                        </dd>
                                    <?php endforeach; ?>
                                    </dl>

                                    <div class="btns-swatches">
                                        <a class="btn-more" href>More</a>
                                        <a class="btn-less" href>Less</a>
                                    </div>
                                </div>
                            <?php endif; ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image alt-img">

                                <?php 
				  if(isset($_imgSize)&&isset($_filterColor)){
				  $productImages = $_bornProductListHelper->getProductImages($_product, $_imgSize, null, $_filterColor);
				  }elseif(isset($_imgSize)&&!isset($_filterColor)){
				  $productImages = $_bornProductListHelper->getProductImages($_product, $_imgSize, null, null);
				  }elseif(!isset($_imgSize)&&isset($_filterColor)){
				  $productImages = $_bornProductListHelper->getProductImages($_product, null, null, $_filterColor);
				  }elseif(!isset($_imgSize)&&!isset($_filterColor)){
				  $productImages = $_bornProductListHelper->getProductImages($_product,null, null, null);
				  }
                                 
                                ?>

                                <img class="product-image-default" id="product-collection-image-<?php echo $_product->getId(); ?>"
                                     src="<?php echo $productImages['small_image'] ?>"
                                     alt="<?php echo $productImages['label'] ?>" />

                                <?php if (array_key_exists('alt_image',$productImages) && $productImages['alt_image']) : ?>
                                    <img class="product-image-hover bg" src="<?php echo $productImages['alt_image'] ?>" alt="<?php echo $productImages['label'] ?>"/>
                                <?php else: ?>
                                    <img class="product-image-hover bg" id="product-collection-image-<?php echo $_product->getId(); ?>"
                                         src="<?php echo $productImages['small_image'] ?>"
                                         alt="<?php echo $productImages['label'] ?>" />
                                <?php endif ?>
                            </a>
                            <div class="btns">
                                <a class="quickview" data-coherent-modal data-modal-name="quickview-php" data-modal-id="<?php echo $_product->getId() ?>"><?php echo $this->__('Quick View')?></a>
                                <a data-formkey="<?php echo $this->helper('wishlist')->getFormKey() ?>" class="link-wishlist wishlist <?php if($this->inWishlist($_product)) echo 'favorite' ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Favorite')?></a>
                            </div>

                            <div class="product-info">

                                <?php if($productBage = $this->getProductBadge($_product)): ?>
                                    <div class="tag-new"><?php echo $productBage ?></div>
                                    <?php $productBage = null; ?>
                                <?php elseif ($_bornProductListHelper->isNewProduct($_product)): ?>
                                    <div class="tag-new"><?php echo $this->__('New') ?></div>
                                <?php endif ?>

                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                                <?php if ($_subText = $this->getSubText($_product)): ?>
                                    <p class="product-subtitle"><?php echo $_subText ?></p>
                                <?php endif ?>
                                <?php 
                                echo $this->getReviewsSummaryHtml($_product, 'short');
                                if ($this->getChild('name.after')) {
                                    $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                    foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                        $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                        $_nameAfterChild->setProduct($_product);
                                        echo $_nameAfterChild->toHtml();
                                    }
                                }
                                ?>
                                <?php echo $this->getPriceHtml($_product, true) ?>
                                <?php if($_product->getRatingSummary()): ?>
                                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                <?php endif; ?>
                                 <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?> 
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            <?php /*if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            <?php endif*/ ?>
            <?php $i++ ?>
        <?php endforeach ?>
    </ul>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

</div>
<?php endif; ?>
<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
$productArray = json_encode($productArray);
?>
<script type="text/javascript">
    var productArrayString = '<?php echo $productArray; ?>';
    var productArrayObject = JSON.parse(productArrayString);
    productArrayObject.forEach(function(item){
        ga('ec:addImpression', {
            'id': item.sku,
            'name': item.name,
            'brand': item.brand,
            'list': 'Category Results',
            'position': item.position
        });         
    }); 
</script>