<?php
/**
 * @see Qualityunit_Pap_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="pap-notice">
  <?php
    echo Mage::helper('pap')->__('In case you need a help with the setup, feel free to get in touch with us - see <a href="https://www.qualityunit.com/company/contact-us/" target="_parent">our website</a> or <a href="mailto:support@qualityunit.com?Subject=Problems%20with%20Magento%20module,%20ver.%20%s">email us</a> directly.', $this->getPapVersion());
  ?>
</div>