<?php

$_code = $this->getMethodCode();
$tokenCards = $this->getTokenCards();
$cTokens = ($tokenCards->getSize()>0 && $this->canUseToken());
$sageStyle = ($cTokens ? ' style="display:none;"' : '');
$integration = Mage::getStoreConfig(Ebizmarts_SagePaymentsPro_Model_Config::CONFIG_INTEGRATION,Mage::app()->getStore()->getId());
?>
<input type="hidden" id="sagepayments_payment_method" name="sagepayments_payment_method" value="<?php echo $this->htmlEscape($_code); ?>" />
<?php if($integration == Ebizmarts_SagePaymentsPro_Model_Config::INTEGRATION_DIRECT) : ?>
<div id="payment_form_<?php echo $_code ?>" style="display:none;">

    <?php echo $this->getChildHtml(); ?>
    <ul class="form-list paymentsage">

        <?php if($this->canUseToken()): ?>
            <li<?php /*echo $sageStyle;*/ if($tokenCards->getSize()==0 || $cTokens): echo ' style="display:none;"'; endif; ?>>
                <a class="usexist" href="" onclick="toggleNewCard(1); return false;"><?php echo $this->__('Saved Credit Cards'); ?></a>
            </li>
        <?php endif; ?>

        <li<?php echo $sageStyle; ?>>
            <div class="input-box">
                <input style="display: none;">
                <input type="text" title="<?php echo $this->__('Name on Card') ?>" autocomplete="off" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" />
                <label for="<?php echo $_code ?>_cc_owner" class="label-text required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
            </div>
        </li>
        <li<?php echo $sageStyle; ?>>
            <div class="input-box">
                <input style="display: none;">
                <input autocomplete="off" type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
                <label for="<?php echo $_code ?>_cc_number" class="label-text required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
            </div>
        </li>
        <li<?php echo $sageStyle; ?>>
            <label for="<?php echo $_code ?>_cc_type" class="label-text-up required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
            <div class="input-box">
                <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
                    <option value="0"><?php echo $this->__('--Please Select--')?></option>
                    <?php $_ccType = $this->getInfoData('cc_type') ?>
                    <?php foreach ($this->getSagePaymentsAvailableTypes() as $_typeCode => $_typeName): ?>
                        <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </li>
        <li<?php echo $sageStyle; ?> id="<?php echo $_code ?>_cc_type_exp_div">
            <label for="<?php echo $_code ?>_expiration" class="label-text-up required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                        <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'0' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
                <div class="v-fix">
                    <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                    <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                        <?php foreach ($this->getCcYears() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'0' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
        </li>
        <li<?php echo $sageStyle; ?> id="<?php echo $_code ?>_cc_type_cvv_div">
            <div class="input-box">
                <div class="v-fix">
                    <input autocomplete="off" type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
                    <label for="<?php echo $_code ?>_cc_cid" class="label-text required"><em>*</em><?php echo $this->__('CVN') ?></label>
                </div>
                <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>

                <div class="tool-tip" id="payment-tool-tip" style="display:none;">
                    <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Close')) ?>"><span class="icon-ex"></span> </a></div>
                    <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Card Verification Number Visual Reference')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Card Verification Number Visual Reference')) ?>" /></div>
                </div>

            </div>
        </li>
        <script type="text/javascript">
            //<![CDATA[
            function toggleToolTip(event){
                if($('payment-tool-tip')){
                    $('payment-tool-tip').setStyle({
                        top: (Event.pointerY(event)-560)+'px'//,
                        //left: (Event.pointerX(event)+100)+'px'
                    })
                    $('payment-tool-tip').toggle();
                }
                Event.stop(event);
            }
            if($('payment-tool-tip-close')){
                Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
            }
            //]]>
        </script>

        <?php if($this->canUseToken()): ?>
            <li<?php echo $sageStyle; ?> class="input-box remember-for-next-time">
                <input checked="checked" type="checkbox" name="payment[remembertoken]" value="1" id="remembertoken-<?php echo $_code; ?>" />
                <label class="label-text" for="remembertoken-<?php echo $_code; ?>"><?php echo $this->__('Do you wish to have your credit card details remembered for faster checkout next time?'); ?></label>&nbsp;
            </li>
        <?php endif; ?>
    </ul>
</div>
<?php else: ?>
<div id="payment_form_<?php echo $_code ?>" style="display:none;">
    <ul class="form-list">
        <li>You will be redirected to SagePayments site on Place Order</li>
    </ul>
    <?php echo $this->getChildHtml(); ?>
    <ul class="form-list paymentsage">
        <?php if($this->canUseToken()): ?>
            <li<?php /*echo $sageStyle;*/ if($tokenCards->getSize()==0 || $cTokens): echo ' style="display:none;"'; endif; ?>>
                <a class="usexist" href="" onclick="toggleNewCard(1); return false;"><?php echo $this->__('Saved Credit Cards'); ?></a>
            </li>
        <?php endif; ?>
        <?php if($this->canUseToken()): ?>
            <li<?php echo $sageStyle; ?>>
                <label for="remembertoken-<?php echo $_code; ?>"><?php echo $this->__('Do you wish to have your credit card details remembered for faster checkout next time?'); ?></label>&nbsp;
                <input checked="checked" type="checkbox" name="payment[remembertoken]" value="1" id="remembertoken-<?php echo $_code; ?>" />
            </li>
        <?php endif; ?>
    </ul>
</div>
<?php endif; ?>