<?php
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$_helper = $this->helper('shadeguide');
$currentStep = $this->getCurrentStep();
$currentStepOptions = $this->getStepOptions($currentStep);
$currentStepId = $this->getCurrentStepId();
$disabled = $currentStepId == 1 ? false: true;
?>
<div class="options-wrapper <?php echo $currentStep['template'] ?>" data-attr="<?php echo $currentStep['product_attribute'] ?>">
    <?php $optionSelect = $currentStep['multiselect'] ? 'checkbox-select' : 'option-select'; ?>
    <?php foreach ($currentStepOptions as $option): ?>
        <div class="fieldset">
            <div class="field-wrapper">
                <div class="field">
                    <?php if (!$currentStep['multiselect']): ?>
                        <input
                            class="input-radio option-<?php echo $option['value']; ?>"
                            type="radio"
                            name="<?php echo $currentStep['product_attribute']; ?>"
                            value="<?php echo $option['value']; ?>"
                            <?php echo $disabled ? 'disabled="disabled"' : ''; ?>
                        />
                    <?php else: ?>
                        <input
                            class="input-checkbox option-<?php echo $option['value']; ?>"
                            type="checkbox"
                            name="<?php echo $currentStep['product_attribute']; ?>"
                            value="<?php echo $option['value']; ?>"
                            <?php echo $disabled ? 'disabled="disabled"' : ''; ?>
                        />
                    <?php endif; ?>
                    <label for="option-<?php echo $option['value']; ?>" class="label <?php echo $optionSelect ?> option-<?php echo $option['value']; ?> <?php echo $disabled ? 'disabled' : '' ?>">
                        <?php echo $option['label']; ?>
                    </label>
                </div>
                <?php $cmsIdentifier = $_helper->convertOptionLabel($option['label']); ?>
                <?php $optionCms = $_helper->getAdditionalCmsBlock($currentStep, $cmsIdentifier) ?>
                <?php if ($optionCms): ?>
                    <div class="w additional-cms option-cms">
                        <?php echo $optionCms; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>