<?php
    $items = $this->getItemsAsArray();
    $shades = $this->getShades();

    $shades = $this->getShadeData();
?>
<div class="color-filters static-filter" id="color-filters">
    <h3 class="filter-title mobile-only">Complexion</h3>
    <div class="color-range">
        <div class="color-filter__header">
            <h3 class="filter-title">Choose your color range:</h3>
            <a data-coherent-modal data-modal-name="shade-guide" class="shade-guide">Shade Guide
                <span class="icon-shadefinder"><span class="path1"></span><span class="path2"></span><span class="path3"></span><span class="path4"></span><span class="path5"></span></span>
            </a>

            <div class="shade-guide-contents" style="display: none">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pur-shade-guide')->toHtml() ?>
            </div>
        </div>
        <ul class="color-range-list">
             <?php foreach ($shades as $shade): ?>
                <li class="color-range-item" data-color-hex="<?php echo $shade['color_hex'] ?>">
                    <div class="input-box">
                        <input <?php if($this->isActiveColorRange($shade['code'])): ?>checked="checked"<?php endif; ?> type="radio" name="color-range" id="<?php echo $this->getShadeCode($shade['code'],$shade['key']); ?>" hidden>
                        <label for="<?php echo $this->getShadeCode($shade['code'], $shade['key']); ?>" class="label-text"><?php echo $shade['label']; ?></label>
                        <span class="triangle"></span>
                    </div>
                </li>
             <?php endforeach; ?>
        </ul>
    </div>
    <div class="best-match">
        <div class="color-filter__header color-match">
            <h3 class="filter-title">Choose your best match:</h3>

            <a class="undertone-guide" data-coherent-modal data-modal-name="undertone-guide" data-modal-video-link="<?php echo $this->getUnderToneVideoLink() ?>"><?php echo $this->getUnderToneTitle() ?></a>
        </div>

        <ul class="best-match-slider" id="best-match-slider">

            <?php  foreach ($shades as $key =>  $shade): ?>
            <?php $matches = $this->getMatchByShade($shade['code'], $items);
                  $shadeCode=  $this->getShadeCode($shade['code'],$shade['key']);
            ?>
                <?php foreach($matches as $match): ?>
                 <?php

                     $filter_id = $match->getOptionId();
                     if(array_key_exists($filter_id,$items)){
                     $_item = $items[$filter_id];
                     }
                 ?>
                <?php if(isset($_item)): ?>
                    <li class="item filter-slider-item <?php echo $this->getShadeCode($shade['code'],$shade['key']); ?> <?php if($this->isActiveColorRange($shade['code'])): ?> show-on-ajax-load<?php endif; ?>">
                        <div class="image-box">
                            <img src="<?php echo $match->getFilterImageUrl(); ?>" class="image" />
                            <div class="shade-description">
                                <h3><?php echo $_item->getLabel(); ?></h3>
                                <p></p>
                            </div>
                        </div>
                        <!--" class="image">-->
                        <div class="input-box filter" id="filter-<?php echo $_item->getFilter()->getRequestVar() ?>-<?php echo $_item->getValue() ?>">
                            <input type="checkbox" hidden <?php echo $_item->getMSelected() ? 'checked="checked"' : '' ?> data-name="<?php echo $_item->getFilter()->getRequestVar() ?>" data-value="<?php echo $_item->getValue() ?>">
                            <?php if($this->isActiveColorRange($shade['code'])): ?>
                                <label for="<?php echo $_item->getFilter()->getRequestVar() ?>" class="label-text" data-href="<?php echo $this->urlEscape($_item->getMSelected() ? $_item->getRemoveUrl() : $_item->getUrl(true)) ?>"></label>
                            <?php else: ?>
                                <label for="<?php echo $_item->getFilter()->getRequestVar() ?>" class="label-text" data-href="<?php echo $this->urlEscape($_item->getMSelected() ? $_item->getRemoveUrl() : $_item->getUrl(false)) ?>"></label>
                            <?php endif; ?>
                        </div>
                    </li>

                    <?php endif; ?>
					
                <?php endforeach; ?>
            <?php endforeach; ?>
        </ul>

    </div>

</div>