<?php
/**
 * For magento 1.9.1 and above
 */
?>
<?php
/**
 * Template for filter items block
 *
 * @see Mage_Catalog_Block_Layer_Filter
 */
$_dimHelper = Mage::helper('configurableswatches/swatchdimensions');
$_swatchInnerWidth = $_dimHelper->getInnerWidth(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_LAYER);
$_swatchInnerHeight = $_dimHelper->getInnerHeight(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_LAYER);
$_swatchOuterWidth = $_dimHelper->getOuterWidth(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_LAYER);
$_swatchOuterHeight = $_dimHelper->getOuterHeight(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_LAYER);


$_helper = $this->helper('weltpixel_layerednavigation');
$showAttributesCount = $_helper->showProductCountOnAttributes();

$itemsDisplay = $_helper->getItemsDisplay();
$itemLimit = $_helper->getItemLimit();

$index = 0;
$showMoreLess = false;
?>

<ol class="configurable-swatch-list">
    <?php foreach ($this->getItems() as $_item): ?>
        <?php $index += 1; ?>
        <?php
        $_hasItems = ($_item->getCount() > 0);
        $_label = $_item->getLabel();
        $_swatchUrl = Mage::helper('configurableswatches/productimg')->getGlobalSwatchUrl($_item, $_label, $_swatchInnerWidth, $_swatchInnerHeight);
        $_hasImage = (!empty($_swatchUrl));
        $_linkClass = 'swatch-link' . (($_hasImage) ? ' has-image' : '');
        $_linkCss = 'height:' . $_swatchOuterHeight . 'px; ' . ((!$_hasImage) ? 'min-' : '') . 'width:' . $_swatchOuterWidth . 'px;';
        $_lineHeight = $_swatchOuterHeight + 2;
        ?>
        <li<?php if ($_hasImage) {
        echo ' style="line-height: ' . $_lineHeight . 'px;"';
    } ?> class=" <?php
    if ($itemsDisplay && $itemLimit && ($index > $itemLimit)) : $showMoreLess = true;
        echo 'attribute_more_less';
    endif;
    ?>">
                    <?php if ($_hasItems): ?>
                <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>" class="<?php echo $_linkClass ?>">
                        <?php else: ?>
                    <span class="<?php echo $_linkClass ?>">
                        <?php endif; ?>
                    <span class="swatch-label"<?php if ($_hasImage) {
                            echo ' style="' . $_linkCss . '"';
                        } ?>>
                    <?php if ($_hasImage): ?>
                            <img src="<?php echo $_swatchUrl; ?>" alt="<?php echo $_label; ?>" title="<?php echo $_label ?>" width="<?php echo $_swatchInnerWidth ?>" height="<?php echo $_swatchInnerHeight ?>" />
                    <?php else: ?>
                        <?php echo $_label; ?>
                    <?php endif; ?>
                    </span>
            <?php if ($showAttributesCount): ?>
                        <span class="count">(<?php echo $_item->getCount() ?>)</span>
            <?php endif; ?>
        <?php if ($_hasItems): ?>
                </a>
        <?php else: ?>
                </span>
    <?php endif; ?>
        </li>
    <?php endforeach ?>
    <?php if (!$_helper->isMobileOrTablet()): ?>
    <?php if ($showMoreLess) : ?>
            <li class="show_more"><span> <?php echo $this->__('More'); ?> &nbsp; <i class="ion-chevron-down"></i></span></li>
            <li class="show_less"><span> <?php echo $this->__('Less'); ?> &nbsp; <i class="ion-chevron-up"></i></span></li>
    <?php endif; ?>
<?php endif; ?>
</ol>
