<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<div class="hightlights-wrap">
    <div class="hightlights-side">
        <div class="hightlights-side-inner">
            <div class="description">
                <?php echo $_product->getDescription(); ?>
            </div>
        </div>
    </div>
    <?php if($_product->getData('description_video_image') && $_product->getData('description_video_image') != 'no_selection') : ?>
        <?php $_product->setHighlightVideoLink(false) ?>
        <div class="hightlights-side">
        <?php if ($_product->getDescriptionVideoLink()): ?>            
            <div class="video" data-link="<?php echo $_product->getDescriptionVideoLink(); ?>">
                <div class="title"><?php echo $_product->getName() ?></div>
                <img class="alt yt-video-bg" src="<?php echo $this->helper('catalog/image')->init($_product, 'description_video_image'); ?>" width="" height="" alt="<?php $this->stripTags($_product->getName(), null, true) ?>" />

                <iframe class="yt-video" width="100%" height="350px" src="https://www.youtube.com/embed/<?php
                $x = explode('/', $_product->getVideoLink());
                echo $y = array_pop($x);
                ?>"
                data-autoplay-src="https://www.youtube.com/embed/<?php
                $x = explode('/', $_product->getDescriptionVideoLink());
                echo $y = array_pop($x);
                ?>?autoplay=1&showinfo=0&controls=0" frameborder="0" allowfullscreen></iframe>

                <p class="image-label yt-video-starter"><?php echo $this->getCmsDescriptionVideoLabel() ?></p>
            </div>
        <?php else: ?>
            <div class="image">
                <img class="highlight-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'description_video_image'); ?>" width="" height="" alt="<?php $this->stripTags($_product->getName(), null, true) ?>" />
            </div>
        <?php endif ?>
        </div>
    <?php endif; ?>
</div>
