<?php
if($_SERVER['HTTP_HOST']=='www.purcosmetics.com'){
$uri = 'www.purcosmetics.com';
$domainstyle = 'pur';
}elseif($_SERVER['HTTP_HOST']=='www.cosmedix.com'){
$uri = 'www.cosmedix.com';
$domainstyle = 'cos';
}else{
$uri = 'www.purcosmetics.com';
$domainstyle = 'pur';
}
if(!isset($_COOKIE['visitor'])){
$visitor = true;
}

if(isset($_COOKIE['visitor'])){
$visitor = true;
}
//Mage::getModel(‘core/cookie’)->set("visitor", true, time()+86400,'/',$uri,0,0);
?>
<!DOCTYPE html>
<html>
<head>

<?php echo $this->getChildHtml('head') ?>
</head>
<body class="page-print<?php echo $this->getBodyClass()?$this->getBodyClass():'' ?>">
<div>
    <div class="print-head">
        <img src="<?php echo $this->getPrintLogoUrl() ? $this->getPrintLogoUrl() : $this->getChild('header')->getLogoSrc() ?>" class="logo" alt="" />
        <?php if ($this->getPrintLogoText()):?>
            <address><?php echo nl2br($this->escapeHtml($this->getPrintLogoText())) ?></address>
        <?php endif;?>
    </div>
    <?php echo $this->getChildHtml('content') ?>
    <div class="buttons-set">
        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Close Window')) ?>" class="button" onclick="window.close();"><span><span><?php echo $this->__('Close Window') ?></span></span></button>
    </div>
    <?php echo $this->getAbsoluteFooter() ?>
</div>
</body>
</html>
