<?php
$_useRetina = Mage::getStoreConfig('weltpixel_selector/customization_settings/retina');
$_imgSize = 270;
?>

<?php if ($this->hasItems()): ?>
<div class="crosssell" style="float: left">
    <div class="heading-block center">
        <h3><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h3>
    </div>    
    <div id="targetrule-crossell-products" class="products-grid ">
        <?php foreach ($this->getItemCollection() as $_product): ?>
            <div class="item">
                <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->escapeHtml($_product->getName()); ?>">
                    <img
                        src = "<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                        data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                        <?php if ($_useRetina) : ?>
                            data-src-retina = "<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(2 * $_imgSize); ?>"
                        <?php endif; ?>
                        alt="<?php echo $this->escapeHtml($_product->getName()); ?>"
                        /></a>
                <h4><a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->escapeHtml($_product->getName()); ?>"><?php echo $this->escapeHtml($_product->getName()); ?></a></h4>
                <?php echo $this->getPriceHtml($_product, true, '-targetrule-crossell'); ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>
     <script>
        // <![CDATA[
        jQuery(document).ready(function($) {
            var owl = $("#targetrule-crossell-products");
            owl.owlCarousel({
                items: 5,
                pagination: false,
                rewindNav: false,
                lazyLoad : true,
                navigation: true,
                navigationText: [
                    '<i class="icon-angle-left"></i>',
                    '<i class="icon-angle-right"></i>'
                ]
            });
        });
        // ]]>
    </script>
    
<?php endif; ?>