<div class="one-page-form">
    <h2 class="section-title">One Page Order Form</h2>

    <div class="one-page-nav">
        <ul class="one-page-menu">
            <li class="current">
                <a href="#">Promotians</a>
            </li>
            <li>
                <a href="#">Skin Care</a>
            </li>
            <li>
                <a href="#">Professional Peels / Masks</a>
            </li>
            <li>
                <a href="#">Training</a>
            </li>
            <li>
                <a href="#">Business Building</a>
            </li>
        </ul>

        <a class="link-how-to" href="#">How to Use this Form <span class="icon-info"></span> </a>
    </div>

    <form class="one-page-content">
        <!--  Promotions -->
        <div class="one-page-block promotions">
            <h3 class="block-title">Promotions</h3>

            <div class="block-content">
                <div class="block-content-wrap">
                    <ul class="tier-pricing">
                        <li>1-11</li>
                        <li>12-23</li>
                        <li>24+</li>
                        <li>QTY</li>
                        <li>Total</li>
                    </ul>

                    <ul class="products-list">
                        <li class="promotions-product">
                            <div class="product-image left">
                                <img src="" alt="img">
                            </div>
                            <div class="product-name left">
                                <a href="#">Serum 16 and Cell ID Duo</a>
                            </div>
                            <table class="product-pricing right">
                                <tbody><tr>
                                    <td><div data-from="1" data-to="11">$50.00</div></td>
                                    <td><div data-from="12" data-to="23">$49.00</div></td>
                                    <td><div data-from="24">$48.00</div></td>
                                    <td><input type="text" class="qty-promotion" value="3" pattern="^[0-9]+$"></td>
                                    <td><div class="total-price">$150.00</div></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td><a class="link-edit-qty" href="#">Edit</a></td>
                                    <td><a class="link-update-total" href="#">Update</a></td>
                                </tr>
                            </tbody></table>
                            <div class="product-sku right">#8998109</div>
                        </li>
                        <li class="promotions-product">
                            <div class="product-image left">
                                <img src="" alt="img">
                            </div>
                            <div class="product-name left">
                                <a href="#">Serum 16 and Cell ID Duo</a>
                            </div>
                            <table class="product-pricing right">
                                <tbody><tr>
                                    <td><div data-from="1" data-to="11">$50.00</div></td>
                                    <td><div data-from="12" data-to="23">$49.00</div></td>
                                    <td><div data-from="24">$48.00</div></td>
                                    <td><input type="text" class="qty-promotion" value="3" pattern="^[0-9]+$"></td>
                                    <td><div class="total-price">$150.00</div></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td><a class="link-edit-qty" href="#">Edit</a></td>
                                    <td><a class="link-update-total" href="#">Update</a></td>
                                </tr>
                            </tbody></table>
                            <div class="product-sku right">#8998109</div>
                        </li>
                    </ul>
                </div>

            </div>
        </div>

        <!--  Skincare -->
        <div class="one-page-block skincare">
            <h3 class="block-title">Skincare</h3>
            <ul class="refinements">
                <li class="input-box">
                    <input id="refinement1" type="checkbox" name="refinement" checked="" hidden="">
                    <label for="refinement1" class="label-text">All</label>
                </li>
                <li class="input-box">
                    <input id="refinement2" type="checkbox" name="refinement" hidden="">
                    <label for="refinement2" class="label-text">Retail</label>
                </li>
                <li class="input-box">
                    <input id="refinement3" type="checkbox" name="refinement" hidden="">
                    <label for="refinement3" class="label-text">Backbar</label>
                </li>
                <li class="input-box">
                    <input id="refinement4" type="checkbox" name="refinement" hidden="">
                    <label for="refinement4" class="label-text">Testers</label>
                </li>
            </ul>

            <div class="block-content">
                <div class="block-content-wrap">
                    <ul class="tier-pricing">
                        <li>1-11</li>
                        <li>12-23</li>
                        <li>24+</li>
                        <li>QTY</li>
                        <li>Total</li>
                    </ul>

                    <ul class="products-list">
                        <li class="skincare-subtitle">Moisturizers</li>
                        <li class="skincare-product">
                            <div class="product-image left">
                                <img src="" alt="img">
                            </div>
                            <div class="product-name left">
                                <a href="#">Serum 16 and Cell ID Duo</a>
                            </div>
                            <table class="product-pricing right">
                                <tbody><tr>
                                    <td><div data-from="1" data-to="11">$50.00</div></td>
                                    <td><div data-from="12" data-to="23">$49.00</div></td>
                                    <td><div data-from="24">$48.00</div></td>
                                    <td><input type="text" class="qty-promotion" value="3" pattern="^[0-9]+$"></td>
                                    <td><div class="total-price">$150.00</div></td>
                                </tr>
                                <tr>
                                    <td><div data-from="1" data-to="11" data-tester="30">$15.40</div></td>
                                    <td><div data-from="12" data-to="23"></div></td>
                                    <td><div data-from="24"></div></td>
                                    <td><input type="text" class="qty-promotion" value="" pattern="^[0-9]+$"></td>
                                    <td><div class="total-price"></div></td>
                                </tr>
                                <tr>
                                    <td><div data-from="1" data-to="11" data-gwp="15">$12.00</div></td>
                                    <td><div data-from="12" data-to="23"></div></td>
                                    <td><div data-from="24"></div></td>
                                    <td><input type="text" class="qty-promotion" value="" pattern="^[0-9]+$"></td>
                                    <td><div class="total-price"></div></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td><a class="link-edit-qty" href="#">Edit</a></td>
                                    <td><a class="link-update-total" href="#">Update</a></td>
                                </tr>
                            </tbody></table>
                            <ul class="product-sku right">
                                <li class="size-variant">1 oz: #8998109</li>
                                <li class="size-variant">30ml Tester: #8998109</li>
                                <li class="size-variant">15ml GWP: #8998109</li>
                            </ul>
                        </li>
                        <li class="skincare-subtitle">Serums</li>
                        <li class="skincare-product">
                            <div class="product-image left">
                                <img src="" alt="img">
                            </div>
                            <div class="product-name left">
                                <a href="#">Serum 16 and Cell ID Duo</a>
                            </div>
                            <table class="product-pricing right">
                                <tbody><tr>
                                    <td><div data-from="1" data-to="11">$50.00</div></td>
                                    <td><div data-from="12" data-to="23">$49.00</div></td>
                                    <td><div data-from="24">$48.00</div></td>
                                    <td><input type="text" class="qty-promotion" value="3" pattern="^[0-9]+$"></td>
                                    <td><div class="total-price">$150.00</div></td>
                                </tr>
                                <tr>
                                    <td><div data-from="1" data-to="11" data-tester="30">$15.40</div></td>
                                    <td><div data-from="12" data-to="23"></div></td>
                                    <td><div data-from="24"></div></td>
                                    <td><input type="text" class="qty-promotion" value="" pattern="^[0-9]+$"></td>
                                    <td><div class="total-price"></div></td>
                                </tr>
                                <tr>
                                    <td><div data-from="1" data-to="11" data-gwp="15">$12.00</div></td>
                                    <td><div data-from="12" data-to="23"></div></td>
                                    <td><div data-from="24"></div></td>
                                    <td><input type="text" class="qty-promotion" value="" pattern="^[0-9]+$"></td>
                                    <td><div class="total-price"></div></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td><a class="link-edit-qty" href="#">Edit</a></td>
                                    <td><a class="link-update-total" href="#">Update</a></td>
                                </tr>
                            </tbody></table>
                            <ul class="product-sku right">
                                <li class="size-variant">1 oz: #8998109</li>
                                <li class="size-variant">30ml Tester: #8998109</li>
                                <li class="size-variant">15ml GWP: #8998109</li>
                            </ul>
                        </li>
                        <li class="skincare-subtitle">Eye Care</li>
                        <li class="skincare-product">
                            <div class="product-image left">
                                <img src="" alt="img">
                            </div>
                            <div class="product-name left">
                                <a href="#">Serum 16 and Cell ID Duo</a>
                            </div>
                            <table class="product-pricing right">
                                <tbody><tr>
                                    <td><div data-from="1" data-to="11">$50.00</div></td>
                                    <td><div data-from="12" data-to="23">$49.00</div></td>
                                    <td><div data-from="24">$48.00</div></td>
                                    <td><input type="text" class="qty-promotion" value="3" pattern="^[0-9]+$" <="" td="">
                                    </td><td><div class="total-price">$150.00</div></td>
                                </tr>
                                <tr>
                                    <td><div data-from="1" data-to="11" data-tester="30">$15.40</div></td>
                                    <td><div data-from="12" data-to="23"></div></td>
                                    <td><div data-from="24"></div></td>
                                    <td><input type="text" class="qty-promotion" value="" pattern="^[0-9]+$"></td>
                                    <td><div class="total-price"></div></td>
                                </tr>
                                <tr>
                                    <td><div data-from="1" data-to="11" data-gwp="15">$12.00</div></td>
                                    <td><div data-from="12" data-to="23"></div></td>
                                    <td><div data-from="24"></div></td>
                                    <td><input type="text" class="qty-promotion" value="" pattern="^[0-9]+$"></td>
                                    <td><div class="total-price"></div></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td><a class="link-edit-qty" href="#">Edit</a></td>
                                    <td><a class="link-update-total" href="#">Update</a></td>
                                </tr>
                            </tbody></table>
                            <ul class="product-sku right">
                                <li class="size-variant">1 oz: #8998109</li>
                                <li class="size-variant">30ml Tester: #8998109</li>
                                <li class="size-variant">15ml GWP: #8998109</li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="button-set">
            <div class="block-content-wrap">
                <button class="button btn-checkout">Check Out</button>
            </div>
        </div>

    </form>

</div>
